### ISSUE TITLE
UI Clarity Problems

### ISSUE THREAD

**Issue by RFerzoco** [GDauterman/rpi_beefcake#32]
When you enter new goals on the web page, the size of the pop-up menu is massive compared to the other pop-ups in the app. 

Not terrible but it is a massive white box so it looks pretty bad.

**Comment by RFerzoco** [comment]
On the data entry pop up for the nutrition data we aren't showing users what unit to enter information as.

This is just to increase clarity for the user so it is low prio, but should still be addressed.

**Comment by RFerzoco** [comment]
On the Workout logging page in the desktop/webpage version. The Add Set and Log Workout buttons are very close and look messy.

Very low prio, just think it should be adjusted.

**Comment by RFerzoco** [comment]
In dark mode, Daily Report is difficult to read

Similarly for the change goal pop-ups the words are invisible because the pop-up box is still all white

**Comment by RFerzoco** [comment]
Starting Values for Protein, Fat, and Carb goals are "not the most realistic"

**Comment by RFerzoco** [comment]
We still need to update sleep quality to be generic options instead of entering a number

**Comment by RFerzoco** [comment]
The Goals page should be a person Icon instead of the scale icon (at least in my opinion)

Regardless the scale icon is not super readable so I think we should change it to something.

**Comment by RFerzoco** [comment]
Upon going over on a goal, change the progress bar color to Red to show that it went over instead of just filling it

**Comment by RFerzoco** [comment]
On Workout Page, if the User attempts to submit data with some rows being null we aren't displaying an error to show the User that nothing is being saved.

In addition we are still saving "notes" to the document with nowhere to enter that information.

**Comment by RFerzoco** [comment]
Can't see username or password characters when trying to login in dark mode

**Comment by GDauterman** [comment]
Broken down into multiple separate issues, most closed already
